# : Manager [[[

[mgr]
cwd = { fg = "#D8DEE9" }  # nord4

# Tab
tab_active = { fg = "#2E3440", bg = "#88C0D0", bold = true }       # nord0 / nord8
tab_inactive = { fg = "#ECEFF4", bg = "#2E3440" }                 # nord6 / nord0
tab_width = 1

# Find
find_keyword = { fg = "#BF616A", bold = true, italic = true, underline = true }  # nord11
find_position = { fg = "#BF616A", bold = true, italic = true }                  # nord11

# Marker
marker_copied = { fg = "#B48EAD", bg = "#B48EAD" }      # nord15
marker_cut = { fg = "#A3BE8C", bg = "#A3BE8C" }         # nord14
marker_marked = { fg = "#BF616A", bg = "#BF616A" }      # nord11
marker_selected = { fg = "#D08770", bg = "#D08770" }    # nord12

# Count
count_copied = { fg = "#2E3440", bg = "#A3BE8C" }       # nord0 / nord14
count_cut = { fg = "#2E3440", bg = "#A3BE8C" }          # nord0 / nord14
count_selected = { fg = "#2E3440", bg = "#D08770" }     # nord0 / nord12

# Border
border_symbol = " "
border_style  = { fg = "#88C0D0" }                      # nord8

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
[mode]
# Mode
normal_main = { bg = "#88C0D0", fg = "#2E3440", bold = true }   # nord8 / nord0
normal_alt  = { bg = "#4C566A", fg = "#E5E9F0" }               # nord3 / nord5

# Select mode
select_main = { bg = "#81A1C1", fg = "#3B4252", bold = true }   # nord9 / nord1
select_alt  = { bg = "#4C566A", fg = "#E5E9F0" }               # nord3 / nord5

# Unset mode
unset_main = { bg = "#B48EAD", fg = "#434C5E", bold = true }    # nord15 / nord2
unset_alt  = { bg = "#4C566A", fg = "#E5E9F0" }                # nord3 / nord5

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#88C0D0", bg = "#3B4252" }            # nord8 / nord1
progress_error = { fg = "#BF616A", bg = "#3B4252" }             # nord11 / nord1

# Permissions
permissions_t = { fg = "#8FBCBB" }      # nord7
permissions_w = { fg = "#B48EAD" }      # nord15
permissions_x = { fg = "#BF616A" }      # nord11
permissions_r = { fg = "#8FBCBB" }      # nord7
permissions_s = { fg = "#88C0D0" }      # nord8

# : ]]]


# : Select [[[

[select]
border = { fg = "#88C0D0" }             # nord8
active = { fg = "#D08770", bold = true } # nord12
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#88C0D0" }             # nord8
value = { fg = "#D8DEE9" }              # nord4

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#88C0D0", bg = "#2E3440" }  # nord8 / nord0

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#88C0D0" }             # nord8
title = {}
hovered = { fg = "#A3BE8C", underline = true }  # nord14

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3B4252" }               # nord1
cand = { fg = "#88C0D0" }               # nord8
rest = { fg = "#2E3440" }               # nord0
desc = { fg = "#D8DEE9" }               # nord4
separator = " ▶ "
separator_style = { fg = "#D8DEE9" }    # nord4

# : ]]]


# : Help [[[

[help]
on = { fg = "#D8DEE9" }                 # nord4
run = { fg = "#D8DEE9" }                # nord4
footer = { fg = "#3B4252", bg = "#81A1C1" }  # nord1 / nord9

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#D08770" }         # nord12
title_warn = { fg = "#88C0D0" }         # nord8
title_error = { fg = "#BF616A" }        # nord11

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#88C0D0" },           # nord8

  # Media
  { mime = "{audio,video}/*", fg = "#EBCB8B" },   # nord13

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#B48EAD" },  # nord15

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#A3BE8C" },  # nord14

  # Special files
  { name = "*", is = "orphan", bg = "#BF616A" },  # nord11
  { name = "*", is = "exec", fg = "#ECEFF4" },    # nord6

  # Fallback
  { name = "*", fg = "#D8DEE9" },                 # nord4
  { name = "*/", fg = "#88C0D0" },                # nord8
]

# : ]]]
